export const defaultState = {
  scenario: 'temperateTempo',
  activity: 'tempoRun',
  effort: 7,
  sweat: 7,
  temp: 24,
  humidity: 60,
  wind: 8,
  sun: 4,
  materialA: 'perforatedCotton',
  fitA: 'regular',
  patternA: 'mothTechStyle',
  materialB: 'polyester',
  fitB: 'athletic',
  patternB: 'none',
  materialC: 'meshPoly',
  fitC: 'loose',
  patternC: 'microGrid',
  validationProtocol: 'runFieldTest',
  view: 'thermal'
};
